#[derive(Debug, Clone, Copy)]
pub enum MsgReq {
    rd_build_compiler,
    wr_build_compiler(&'static str),
    rd_build_git,
    wr_build_git(&'static str),
    rd_build_host,
    wr_build_host(&'static str),
    rd_build_profile,
    wr_build_profile(&'static str),
    rd_build_target,
    wr_build_target(&'static str),
    rd_build_time,
    wr_build_time(&'static str),
    rd_build_version,
    wr_build_version(&'static str),
    rd_calib_acc_b,
    wr_calib_acc_b(i32),
    rd_calib_acc_k,
    wr_calib_acc_k(i32),
    rd_calib_ecg_b,
    wr_calib_ecg_b(i32),
    rd_calib_ecg_k,
    wr_calib_ecg_k(i32),
    rd_calib_reo_b,
    wr_calib_reo_b(i32),
    rd_calib_reo_k,
    wr_calib_reo_k(i32),
    rd_conf_cyclic,
    wr_conf_cyclic(bool),
    rd_conf_time,
    wr_conf_time(u32),
    rd_ctrl_erase,
    wr_ctrl_erase(()),
    rd_ctrl_event,
    wr_ctrl_event(&'static [u8]),
    rd_ctrl_goto_loader,
    wr_ctrl_goto_loader(()),
    rd_ctrl_record,
    wr_ctrl_record(bool),
    rd_ctrl_vis,
    wr_ctrl_vis(bool),
    rd_dbg_flags,
    wr_dbg_flags(u32),
    rd_dbg_last,
    wr_dbg_last(&'static str),
    rd_dbg_last_code,
    wr_dbg_last_code(u32),
    rd_desc_serial,
    wr_desc_serial(&'static str),
    rd_desc_type,
    wr_desc_type(&'static str),
    rd_desc_version,
    wr_desc_version(&'static str),
    rd_io_busy,
    wr_io_busy(bool),
    rd_io_file_dir,
    wr_io_file_dir(bool),
    rd_io_file_len,
    wr_io_file_len(u32),
    rd_io_file_max,
    wr_io_file_max(u32),
    rd_io_file_pos,
    wr_io_file_pos(u32),
    rd_io_file_start,
    wr_io_file_start(()),
    rd_io_store_idx,
    wr_io_store_idx(u8),
    rd_io_store_line,
    wr_io_store_line(&'static [u8]),
    rd_io_store_max,
    wr_io_store_max(u32),
    rd_signal_ecg_frq,
    wr_signal_ecg_frq(u8),
    rd_signal_reo_frq,
    wr_signal_reo_frq(u8),
    rd_state_current,
    wr_state_current(i32),
    rd_state_stop_reason,
    wr_state_stop_reason(u32),
    rd_state_voltage,
    wr_state_voltage(i32),
    rd_survey_birth,
    wr_survey_birth(&'static str),
    rd_survey_id,
    wr_survey_id(u32),
    rd_survey_name,
    wr_survey_name(&'static str),
    rd_survey_patient_id,
    wr_survey_patient_id(&'static str),
    rd_survey_patronymic,
    wr_survey_patronymic(&'static str),
    rd_survey_sex,
    wr_survey_sex(&'static str),
    rd_survey_start_time,
    wr_survey_start_time(u32),
    rd_survey_surname,
    wr_survey_surname(&'static str),
    rd_test_echo,
    wr_test_echo(&'static [u8]),
    rd_test_error,
    wr_test_error(&'static str),
    rd_test_test1,
    wr_test_test1(&'static [u8]),
    rd_test_test2,
    wr_test_test2(&'static [u8]),
    rd_test_test3,
    wr_test_test3(&'static [u8]),
    rd_test_test4,
    wr_test_test4(&'static [u8]),
    rd_test_test5,
    wr_test_test5(&'static [u8]),
}
pub fn req2msg(code: RequestCode, path: &str, value: Value) -> Result<MsgReq, ()> {
    match (code, path, value) {
        (RequestCode::READ, "build/compiler", _) => MsgReq::rd_build_compiler,
        (RequestCode::READ, "build/git", _) => MsgReq::rd_build_git,
        (RequestCode::READ, "build/host", _) => MsgReq::rd_build_host,
        (RequestCode::READ, "build/profile", _) => MsgReq::rd_build_profile,
        (RequestCode::READ, "build/target", _) => MsgReq::rd_build_target,
        (RequestCode::READ, "build/time", _) => MsgReq::rd_build_time,
        (RequestCode::READ, "build/version", _) => MsgReq::rd_build_version,
        (RequestCode::READ, "calib/acc/b", _) => MsgReq::rd_calib_acc_b,
        (RequestCode::READ, "calib/acc/k", _) => MsgReq::rd_calib_acc_k,
        (RequestCode::READ, "calib/ecg/b", _) => MsgReq::rd_calib_ecg_b,
        (RequestCode::READ, "calib/ecg/k", _) => MsgReq::rd_calib_ecg_k,
        (RequestCode::READ, "calib/reo/b", _) => MsgReq::rd_calib_reo_b,
        (RequestCode::READ, "calib/reo/k", _) => MsgReq::rd_calib_reo_k,
        (RequestCode::READ, "conf/cyclic", _) => MsgReq::rd_conf_cyclic,
        (RequestCode::READ, "conf/time", _) => MsgReq::rd_conf_time,
        (RequestCode::READ, "ctrl/erase", _) => MsgReq::rd_ctrl_erase,
        (RequestCode::READ, "ctrl/event", _) => MsgReq::rd_ctrl_event,
        (RequestCode::READ, "ctrl/goto_loader", _) => MsgReq::rd_ctrl_goto_loader,
        (RequestCode::READ, "ctrl/record", _) => MsgReq::rd_ctrl_record,
        (RequestCode::READ, "ctrl/vis", _) => MsgReq::rd_ctrl_vis,
        (RequestCode::READ, "dbg/flags", _) => MsgReq::rd_dbg_flags,
        (RequestCode::READ, "dbg/last", _) => MsgReq::rd_dbg_last,
        (RequestCode::READ, "dbg/last_code", _) => MsgReq::rd_dbg_last_code,
        (RequestCode::READ, "desc/serial", _) => MsgReq::rd_desc_serial,
        (RequestCode::READ, "desc/type", _) => MsgReq::rd_desc_type,
        (RequestCode::READ, "desc/version", _) => MsgReq::rd_desc_version,
        (RequestCode::READ, "io/busy", _) => MsgReq::rd_io_busy,
        (RequestCode::READ, "io/file/dir", _) => MsgReq::rd_io_file_dir,
        (RequestCode::READ, "io/file/len", _) => MsgReq::rd_io_file_len,
        (RequestCode::READ, "io/file/max", _) => MsgReq::rd_io_file_max,
        (RequestCode::READ, "io/file/pos", _) => MsgReq::rd_io_file_pos,
        (RequestCode::READ, "io/file/start", _) => MsgReq::rd_io_file_start,
        (RequestCode::READ, "io/store/idx", _) => MsgReq::rd_io_store_idx,
        (RequestCode::READ, "io/store/line", _) => MsgReq::rd_io_store_line,
        (RequestCode::READ, "io/store/max", _) => MsgReq::rd_io_store_max,
        (RequestCode::READ, "signal/ecg/frq", _) => MsgReq::rd_signal_ecg_frq,
        (RequestCode::READ, "signal/reo/frq", _) => MsgReq::rd_signal_reo_frq,
        (RequestCode::READ, "state/current", _) => MsgReq::rd_state_current,
        (RequestCode::READ, "state/stop_reason", _) => MsgReq::rd_state_stop_reason,
        (RequestCode::READ, "state/voltage", _) => MsgReq::rd_state_voltage,
        (RequestCode::READ, "survey/birth", _) => MsgReq::rd_survey_birth,
        (RequestCode::READ, "survey/id", _) => MsgReq::rd_survey_id,
        (RequestCode::READ, "survey/name", _) => MsgReq::rd_survey_name,
        (RequestCode::READ, "survey/patient_id", _) => MsgReq::rd_survey_patient_id,
        (RequestCode::READ, "survey/patronymic", _) => MsgReq::rd_survey_patronymic,
        (RequestCode::READ, "survey/sex", _) => MsgReq::rd_survey_sex,
        (RequestCode::READ, "survey/start_time", _) => MsgReq::rd_survey_start_time,
        (RequestCode::READ, "survey/surname", _) => MsgReq::rd_survey_surname,
        (RequestCode::READ, "test/echo", _) => MsgReq::rd_test_echo,
        (RequestCode::READ, "test/error", _) => MsgReq::rd_test_error,
        (RequestCode::READ, "test/test1", _) => MsgReq::rd_test_test1,
        (RequestCode::READ, "test/test2", _) => MsgReq::rd_test_test2,
        (RequestCode::READ, "test/test3", _) => MsgReq::rd_test_test3,
        (RequestCode::READ, "test/test4", _) => MsgReq::rd_test_test4,
        (RequestCode::READ, "test/test5", _) => MsgReq::rd_test_test5,
        (RequestCode::WRITE, "build/compiler", Value::STR(v)) => MsgReq::wr_build_compiler(v),
        (RequestCode::WRITE, "build/git", Value::STR(v)) => MsgReq::wr_build_git(v),
        (RequestCode::WRITE, "build/host", Value::STR(v)) => MsgReq::wr_build_host(v),
        (RequestCode::WRITE, "build/profile", Value::STR(v)) => MsgReq::wr_build_profile(v),
        (RequestCode::WRITE, "build/target", Value::STR(v)) => MsgReq::wr_build_target(v),
        (RequestCode::WRITE, "build/time", Value::STR(v)) => MsgReq::wr_build_time(v),
        (RequestCode::WRITE, "build/version", Value::STR(v)) => MsgReq::wr_build_version(v),
        (RequestCode::WRITE, "calib/acc/b", Value::I32(v)) => MsgReq::wr_calib_acc_b(v),
        (RequestCode::WRITE, "calib/acc/k", Value::I32(v)) => MsgReq::wr_calib_acc_k(v),
        (RequestCode::WRITE, "calib/ecg/b", Value::I32(v)) => MsgReq::wr_calib_ecg_b(v),
        (RequestCode::WRITE, "calib/ecg/k", Value::I32(v)) => MsgReq::wr_calib_ecg_k(v),
        (RequestCode::WRITE, "calib/reo/b", Value::I32(v)) => MsgReq::wr_calib_reo_b(v),
        (RequestCode::WRITE, "calib/reo/k", Value::I32(v)) => MsgReq::wr_calib_reo_k(v),
        (RequestCode::WRITE, "conf/cyclic", Value::BOOL(v)) => MsgReq::wr_conf_cyclic(v),
        (RequestCode::WRITE, "conf/time", Value::U32(v)) => MsgReq::wr_conf_time(v),
        (RequestCode::WRITE, "ctrl/erase", Value::UNIT(v)) => MsgReq::wr_ctrl_erase(v),
        (RequestCode::WRITE, "ctrl/event", Value::BYTES(v)) => MsgReq::wr_ctrl_event(v),
        (RequestCode::WRITE, "ctrl/goto_loader", Value::UNIT(v)) => MsgReq::wr_ctrl_goto_loader(v),
        (RequestCode::WRITE, "ctrl/record", Value::BOOL(v)) => MsgReq::wr_ctrl_record(v),
        (RequestCode::WRITE, "ctrl/vis", Value::BOOL(v)) => MsgReq::wr_ctrl_vis(v),
        (RequestCode::WRITE, "dbg/flags", Value::U32(v)) => MsgReq::wr_dbg_flags(v),
        (RequestCode::WRITE, "dbg/last", Value::STR(v)) => MsgReq::wr_dbg_last(v),
        (RequestCode::WRITE, "dbg/last_code", Value::U32(v)) => MsgReq::wr_dbg_last_code(v),
        (RequestCode::WRITE, "desc/serial", Value::STR(v)) => MsgReq::wr_desc_serial(v),
        (RequestCode::WRITE, "desc/type", Value::STR(v)) => MsgReq::wr_desc_type(v),
        (RequestCode::WRITE, "desc/version", Value::STR(v)) => MsgReq::wr_desc_version(v),
        (RequestCode::WRITE, "io/busy", Value::BOOL(v)) => MsgReq::wr_io_busy(v),
        (RequestCode::WRITE, "io/file/dir", Value::BOOL(v)) => MsgReq::wr_io_file_dir(v),
        (RequestCode::WRITE, "io/file/len", Value::U32(v)) => MsgReq::wr_io_file_len(v),
        (RequestCode::WRITE, "io/file/max", Value::U32(v)) => MsgReq::wr_io_file_max(v),
        (RequestCode::WRITE, "io/file/pos", Value::U32(v)) => MsgReq::wr_io_file_pos(v),
        (RequestCode::WRITE, "io/file/start", Value::UNIT(v)) => MsgReq::wr_io_file_start(v),
        (RequestCode::WRITE, "io/store/idx", Value::U8(v)) => MsgReq::wr_io_store_idx(v),
        (RequestCode::WRITE, "io/store/line", Value::BYTES(v)) => MsgReq::wr_io_store_line(v),
        (RequestCode::WRITE, "io/store/max", Value::U32(v)) => MsgReq::wr_io_store_max(v),
        (RequestCode::WRITE, "signal/ecg/frq", Value::U8(v)) => MsgReq::wr_signal_ecg_frq(v),
        (RequestCode::WRITE, "signal/reo/frq", Value::U8(v)) => MsgReq::wr_signal_reo_frq(v),
        (RequestCode::WRITE, "state/current", Value::I32(v)) => MsgReq::wr_state_current(v),
        (RequestCode::WRITE, "state/stop_reason", Value::U32(v)) => MsgReq::wr_state_stop_reason(v),
        (RequestCode::WRITE, "state/voltage", Value::I32(v)) => MsgReq::wr_state_voltage(v),
        (RequestCode::WRITE, "survey/birth", Value::STR(v)) => MsgReq::wr_survey_birth(v),
        (RequestCode::WRITE, "survey/id", Value::U32(v)) => MsgReq::wr_survey_id(v),
        (RequestCode::WRITE, "survey/name", Value::STR(v)) => MsgReq::wr_survey_name(v),
        (RequestCode::WRITE, "survey/patient_id", Value::STR(v)) => MsgReq::wr_survey_patient_id(v),
        (RequestCode::WRITE, "survey/patronymic", Value::STR(v)) => MsgReq::wr_survey_patronymic(v),
        (RequestCode::WRITE, "survey/sex", Value::STR(v)) => MsgReq::wr_survey_sex(v),
        (RequestCode::WRITE, "survey/start_time", Value::U32(v)) => MsgReq::wr_survey_start_time(v),
        (RequestCode::WRITE, "survey/surname", Value::STR(v)) => MsgReq::wr_survey_surname(v),
        (RequestCode::WRITE, "test/echo", Value::BYTES(v)) => MsgReq::wr_test_echo(v),
        (RequestCode::WRITE, "test/error", Value::STR(v)) => MsgReq::wr_test_error(v),
        (RequestCode::WRITE, "test/test1", Value::BYTES(v)) => MsgReq::wr_test_test1(v),
        (RequestCode::WRITE, "test/test2", Value::BYTES(v)) => MsgReq::wr_test_test2(v),
        (RequestCode::WRITE, "test/test3", Value::BYTES(v)) => MsgReq::wr_test_test3(v),
        (RequestCode::WRITE, "test/test4", Value::BYTES(v)) => MsgReq::wr_test_test4(v),
        (RequestCode::WRITE, "test/test5", Value::BYTES(v)) => MsgReq::wr_test_test5(v),
    }
}
