[package]
name = "ellocopo2"
version = "0.1.0"
authors = ["Roman M. <m3angreen@gmail.com>"]
edition = "2018"

[features]
default = []
std = []

[dependencies]
num_enum = { version = "0.4.2", default-features = false }
